---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:

  validate-entry:
    name: Validate entries
    uses: ./.github/workflows/validate-entry.yml

  check-file-changes:
    name: Check file changes
    uses: ./.github/workflows/check-file-changes.yml
